/* mkfont.c - turn TrueType fonts into anti-aliased bitmaps for the kernel.
 *
 * The kernel cannot read font files (it has no disk and no FreeType), so we
 * render the glyphs once, at build time, with FreeType and write them out as
 * C arrays: one byte of coverage (0 = transparent, 255 = solid) per pixel.
 * The output, src/font_data.c, is committed, so building SkarletOS does not
 * need FreeType; only regenerating the fonts does.
 *
 * Build:  cc tools/mkfont.c -o build/mkfont $(pkg-config --cflags --libs freetype2)
 * Run:    build/mkfont /usr/share/fonts/truetype/dejavu > src/font_data.c
 *
 * The fonts are DejaVu Sans, DejaVu Sans Bold and DejaVu Sans Mono, whose
 * licence (the Bitstream Vera licence plus public-domain changes) allows
 * embedding and redistribution.
 */
#include <ft2build.h>
#include FT_FREETYPE_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct spec {
    const char *name;  /* C identifier */
    const char *file;  /* TTF file in the font directory */
    int px;            /* pixel size */
    const char *chars; /* characters to include (NULL = printable ASCII) */
};

static const struct spec specs[] = {
    { "font_ui", "DejaVuSans.ttf", 15, NULL },
    { "font_ui_bold", "DejaVuSans-Bold.ttf", 15, NULL },
    { "font_small", "DejaVuSans.ttf", 12, NULL },
    { "font_title", "DejaVuSans-Bold.ttf", 22, NULL },
    { "font_mono", "DejaVuSansMono.ttf", 15, NULL },
    { "font_big", "DejaVuSans.ttf", 56, " 0123456789:" },
    { "font_huge", "DejaVuSans.ttf", 96, " 0123456789:" },
};

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s FONT_DIRECTORY\n", argv[0]);
        return 1;
    }
    FT_Library lib;
    if (FT_Init_FreeType(&lib)) {
        fprintf(stderr, "FreeType init failed\n");
        return 1;
    }
    printf("/* font_data.c - generated by tools/mkfont.c from the DejaVu fonts.\n"
           " * Do not edit by hand. DejaVu fonts: Bitstream Vera licence; DejaVu\n"
           " * changes are in the public domain. See docs/FONT-LICENSE.txt. */\n"
           "#include \"font.h\"\n\n");

    for (size_t s = 0; s < sizeof specs / sizeof specs[0]; s++) {
        const struct spec *sp = &specs[s];
        char path[512];
        snprintf(path, sizeof path, "%s/%s", argv[1], sp->file);
        FT_Face face;
        if (FT_New_Face(lib, path, 0, &face)) {
            fprintf(stderr, "cannot open %s\n", path);
            return 1;
        }
        FT_Set_Pixel_Sizes(face, 0, sp->px);

        /* Pass 1: the coverage bytes. */
        printf("static const unsigned char %s_bits[] = {", sp->name);
        unsigned offsets[128] = { 0 }, total = 0;
        int widths[128], heights[128], xoffs[128], yoffs[128], advs[128];
        memset(widths, 0, sizeof widths);
        int col = 0;
        for (int c = 32; c < 127; c++) {
            int wanted = sp->chars ? strchr(sp->chars, c) != NULL : 1;
            advs[c] = heights[c] = xoffs[c] = yoffs[c] = 0;
            if (!wanted)
                continue;
            if (FT_Load_Char(face, (FT_ULong)c, FT_LOAD_RENDER | FT_LOAD_TARGET_LIGHT)) {
                fprintf(stderr, "no glyph for %c\n", c);
                return 1;
            }
            FT_GlyphSlot g = face->glyph;
            widths[c] = (int)g->bitmap.width;
            heights[c] = (int)g->bitmap.rows;
            xoffs[c] = g->bitmap_left;
            yoffs[c] = g->bitmap_top;
            advs[c] = (int)((g->advance.x + 32) >> 6);
            offsets[c] = total;
            for (int y = 0; y < heights[c]; y++)
                for (int x = 0; x < widths[c]; x++) {
                    if (col++ % 24 == 0)
                        printf("\n   ");
                    printf(" %u,", g->bitmap.buffer[y * g->bitmap.pitch + x]);
                    total++;
                }
        }
        if (total == 0)
            printf(" 0");
        printf("\n};\n\n");

        /* Pass 2: per-glyph metrics. */
        printf("static const struct glyph %s_glyphs[95] = {\n", sp->name);
        for (int c = 32; c < 127; c++)
            printf("    { %d, %d, %d, %d, %d, %u }, /* '%s%c' */\n", widths[c], heights[c],
                   xoffs[c], yoffs[c], advs[c], offsets[c], c == '\\' ? "\\" : "", c);
        printf("};\n\n");

        int ascent = (int)((face->size->metrics.ascender + 63) >> 6);
        int descent = (int)((-face->size->metrics.descender + 63) >> 6);
        int line = (int)((face->size->metrics.height + 63) >> 6);
        printf("const struct font %s = { %d, %d, %d, %d, %s_glyphs, %s_bits };\n\n", sp->name,
               sp->px, ascent, descent, line, sp->name, sp->name);
        FT_Done_Face(face);
    }
    FT_Done_FreeType(lib);
    return 0;
}
